on: push

jobs:
  benchmark:
    runs-on: ubuntu-18.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: '**/extern'
          key: ${{ runner.os }}-${{ hashFiles('**/extern/install.sh') }}
      - run: PREFIX=$(pwd) ./install.sh
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: extern
        env:
          CC: gcc-10
          CXX: g++-10
      - run: mkdir build
      - run: cmake .. -DCMAKE_PREFIX_PATH=$(pwd)/../extern -DCMAKE_BUILD_TYPE=Release && make -j
        working-directory: build
        env:
          CC: gcc-10
          CXX: g++-10
      - run: ./benchmark_kmer --benchmark_repetitions=3
        working-directory: build
      - run: ./benchmark_kmer_counter --benchmark_repetitions=3
        working-directory: build
      - run: ./benchmark_kmer_set --benchmark_repetitions=3
        working-directory: build
      - run: ./benchmark_spss --benchmark_repetitions=3
        working-directory: build
