on: push

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: ./install.sh
        working-directory: extern
        env:
          CC: gcc-10
          CXX: g++-10
          PREFIX: /tmp/usr/local
      - run: mkdir build && cd build && cmake .. -DCMAKE_PREFIX_PATH=/tmp/usr/local -DCMAKE_BUILD_TYPE=Debug -DBoost_ARCHITECTURE=-x64 -DBoost_INCLUDE_DIR=$BOOST_ROOT_1_72_0/include && make -j
        env:
          CC: gcc-10
          CXX: g++-10
      - run: make test
        working-directory: build
