on: push

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/extern'
          key: ${{ runner.os }}-${{ hashFiles('**/extern/install.sh') }}
      - run: PREFIX=$(pwd) ./install.sh
        working-directory: extern
        env:
          CC: gcc-10
          CXX: g++-10
      - run: mkdir build
      - run: cmake .. -DCMAKE_PREFIX_PATH=$(pwd)/../extern -DCMAKE_BUILD_TYPE=Debug && make -j
        working-directory: build
        env:
          CC: gcc-10
          CXX: g++-10
      - run: ctest
        working-directory: build
      - run: ctest --repeat-until-fail 10 -R '.*Random'
        working-directory: build
