on: push

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=/tmp/usr/local && make -j && make install
        working-directory: extern/abseil-cpp
        env:
          CC: gcc-10
          CXX: g++-10
      - run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=/tmp/usr/local && make -j && make install
        working-directory: extern/googletest
        env:
          CC: gcc-10
          CXX: g++-10
      - run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=/tmp/usr/local && make -j && make install
        working-directory: extern/spdlog
        env:
          CC: gcc-10
          CXX: g++-10
      - run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=/tmp/usr/local && make -j && make install
        working-directory: extern/mimalloc
        env:
          CC: gcc-10
          CXX: g++-10
      - run: mkdir build && cd build && cmake .. -DCMAKE_PREFIX_PATH=/tmp/usr/local -DCMAKE_BUILD_TYPE=Debug -DBoost_ARCHITECTURE=-x64 -DBoost_INCLUDE_DIR=$BOOST_ROOT_1_72_0/include && make -j
        env:
          CC: gcc-10
          CXX: g++-10
      - run: ./test_kmer
        working-directory: build
      - run: ./test_kmer_set
        working-directory: build
      - run: ./test_suffix_array
        working-directory: build
      - run: ./test_kmer_set_compact
        working-directory: build
      - run: ./test_range
        working-directory: build
      - run: ./test_graph
        working-directory: build
